apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: sandox
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: ClusterIP # This is the default value
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80 # Port the container is listening on (if unset, defaults to equal port value)

--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeip
  namespace: sandbox
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: NodeIP # This is the default value
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80 # Port the container is listening on (if unset, defaults to equal port value)
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeip
  namespace: sandbox
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: Loadbalancer # This is the default value
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80
